#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace dsd::model {

// One alert generated by AlertManager when a detection matches the alert rule
// (target class + confidence, past the cooldown). Decoupled from the proto
// message: `snapshot` holds the JPEG bytes captured at trigger time and is only
// carried in-process (persisted as a BLOB); it is fetched separately over gRPC.
struct Alert {
    std::int64_t id = 0;              // 0 until persisted, then the SQLite rowid
    std::int64_t camera_id = 0;
    std::string label;               // triggering class, e.g. "person"
    float confidence = 0.0f;         // detection score in [0, 1]
    std::int64_t timestamp_ms = 0;   // when the alert fired
    bool has_snapshot = false;       // an image is stored (may be unloaded here)
    std::vector<std::uint8_t> snapshot;  // JPEG bytes; empty = no image
};

}  // namespace dsd::model
